---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: filebrowser-admin
  namespace: filebrowser
spec:
  encryptedData:
    password: AgBfz9/kJxyHpBligNhSeH5e8ofTUafAPQTc5iluN00x45wUAV//hmFDWkOKzybT8B96Hqu4jzLVTu8Kba49LZR5iHVcZ/vMAJw+4+MeKd+mCeOxTotdrF4t1kq9Z4o4V7AtqyRLxwaZcONU9BEG70SzygOGXa1Bf68uKPjvZYImZCXWV6xsT6+988MIu51wKAdKOt8tYaQRic5cGp/LDXK91//qZdemGWX4M1Q7B0Z9qAd+9fYWnbJeIWCDFLnu/p1BClSVA+uh+61hE0/qLTjvuFs+s24DCYbPAfKApi96rq4eflUOyVLe8YyeLYTX/YqsYM5f+7QbxisffPYpdGkZykfdq3A9/hk/gOsJRwsD2n7urKREZCGFJFftOzK1BfJ5ETAdOqNB/F7m3haDY6ecwDkeUUzNEx2AWPapC9P/gYAzqz7s3NaDWKT2qqnL7mbU3D9BuSt4U/uc3GspLIgHZECWx6BflzSD6uzJUiTwkuDOIQ3gvrc/AmPJ3qIxv2/0hXI6SyaE1nywvSMUbnPWi23f6+vLQi0OjbFNlpcVj3ajvKCSm++mfwZ+y59bfptTlDFiYN5SOiRSQAEP8ryWSEHUilRtXqcglhScf9Y7oh4K+G6mcOis1rGHPBLnK4OhQfBu3LTSgQ9LM9KRb0iZrhCdTXA2+i0Voh1RfKvjC63Z6fwSGQEO1WadY/bde4KjOJzmxwn1PlSFVm33flo2ptKD/X2rnghds3vM
  template:
    metadata:
      name: filebrowser-admin
      namespace: filebrowser
