image:
  repository: ghcr.io/athou/commafeed
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8082

ingress:
  host: feed.voltafinancials.com

db:
  host: postgres.databases.svc.cluster.local
  port: "5432"
  name: commafeed
  user: commafeed

allowRegistrations: true

existingSecret: commafeed-db-secret

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - worker

topologySpread:
  enabled: true


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

