---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: affine-postgres-admin-secret
  namespace: affine
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    postgres-password: AgBaJM2M2pRL2AcrsBhmQUP8ro+ht+g5i38zlxD5loAcLVhtyeiFuPSbXoyWinDaSsTCsodA6KHWsphUuc4zORmOLR9HmSW2W/O/hOwpgqlqJStSqh/6aTm9pc3x/BiXSJG6dQrsl8AdwO81/xVKUJayJMuOUKcI6mTX2DO7Rq41tf2DPRKBktvQJbHEOspCMyRpzvyMYU8vYjHHrX1oWcqt1dobn1FxpXUK4RxHbRqdKddnx60x1GcUUaPMcni7CXqYBI8pooabRC98wUh3wq7DPrg+I/MbpN2qleqJG0AdAC4FHyl5ayR7YPoD37WtLOH+N8vytOlpWRd4c/ngtVuy4ICPiwO/u1eSBBAY6gy7M+M9x0/ibGfCno+cwrbH1SxGqm7Gx/bt5T2O6g0+S1Ecemb/xvT0DG47Lyn4Q3OmJetJwt+jPu333bYEJVNQLYP7g57oFpIH6fq85sZmHD78DBnRvuz2LPUSUirALy0Ma8HOrUAbQAxai2vYIbgH6VE8QrCkk877Sb1gKmJgt2nuMuiLJsTnz+zix3pytvk6fvp1LaSjIqA6CekmkVB2oCajLzkhU2tHhK67TRSRcYUJZ9xqC3ztu8IcJa5wVIcuoZchV9MsQR8zY+Lnu1sQsOeOfcRb/UG7d71Zjy9B00E7V/bPITUBS9LH8Tae37Xw3UvH/OvACgxP6hTEFLycxe0RWEds2sXzdG6k6rkLXl4I3g==
  template:
    metadata:
      name: affine-postgres-admin-secret
      namespace: affine
