apiVersion: apps/v1
kind: Deployment
metadata:
  name: affine
  namespace: affine
  labels:
    app: affine
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: affine
    spec:
      initContainers:
        - name: migration
          image: ghcr.io/toeverything/affine:0.26.3
          command: ["sh", "-c", "node ./scripts/self-host-predeploy.js"]
          env:
            - name: AFFINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: affine-db-secret
                  key: password
            - name: DATABASE_URL
              value: "postgresql://affine:$(AFFINE_DB_PASSWORD)@postgres.databases.svc.cluster.local:5432/affine"
            - name: REDIS_SERVER_HOST
              value: redis-master.databases.svc.cluster.local
            - name: AFFINE_INDEXER_ENABLED
              value: "false"
      containers:
        - name: affine-server
          image: ghcr.io/toeverything/affine:0.26.3
          ports:
            - containerPort: 3010
              protocol: TCP
          env:
            - name: AFFINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: affine-db-secret
                  key: password
            - name: DATABASE_URL
              value: "postgresql://affine:$(AFFINE_DB_PASSWORD)@postgres.databases.svc.cluster.local:5432/affine"
            - name: REDIS_SERVER_HOST
              value: redis-master.databases.svc.cluster.local
            - name: AFFINE_INDEXER_ENABLED
              value: "false"
            - name: PORT
              value: "3010"
            - name: AFFINE_SERVER_EXTERNAL_URL
              value: "https://affine.voltafinancials.com"
          volumeMounts:
            - mountPath: /root/.affine/storage
              name: affine-storage
            - mountPath: /root/.affine/config
              name: affine-config
      restartPolicy: Always
      volumes:
        - name: affine-storage
          persistentVolumeClaim:
            claimName: affine-claim0
        - name: affine-config
          persistentVolumeClaim:
            claimName: affine-claim1
