apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-claim0
  namespace: affine
  labels:
    app: affine
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-hdd
  resources:
    requests:
      storage: 10Gi
