apiVersion: v1
kind: Service
metadata:
  name: affine
  namespace: affine
  labels:
    app: affine
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3010
      targetPort: 3010
  selector:
    app: affine
