---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: affine-postgres-admin-secret
  namespace: affine
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    postgres-password: AgB51QLYkjEZK0uHMhQYI/g7WFc81zm7oHnLerB/8YEx9TjtbSmkJnPLx00GkbdwTPUC7dwWIU8kxso4qgCVFt15IVV6Ky9ClADG1k2VTB2hCYKDDwPAAZjoh89smfXm9xoygHWVZ0ZcF6q0T5sDSw4j9KFOKMjBB2KgahQ9mrJ9yZcIhlGhzHYWLZwIFAr4N5YM6j6hbKjJvlDS48CvjwuJ05M5o0Zvupzbvb2HpaD9tMv3ToQxL4Z3Eodoh7stX7rMtD9YjXKftawImvSLoBpUEGWt9V3li+FwNdFBbykY4tNTpC4WLpM0t4XmoBBUmflqRam3STIQ0fiWrmAUT2Hiy+0bQy6vVqcVgmgQGWjunqYbBYuMGn/o2Wqv1vXJq6dykwE0KLWXj1+6Tx14UEjQ92yxt9hDgUuUC0Uz7xRR9gA3BG78Zc8YgnsqOMB1bvQnTSWqt4kFg0trsJpR6hisw7uLJ0+saYGPq/FXm8J5CyqyyVx0rz+ZHl3x80E/z24LZaNMXZWYU8KukS7xlqToq4/j+7MnSudhuAE0Sw2V0lZDOdupArk0mgLx7KEOVxG9Q48wFZCYoyNTF8iKfk5yFu0Ko8WI2vLyAnfDCMn6Lc44ZKbHnIsIwCaMiaueoAR1Hj/MTqvCtOoUuhBRL6UefK4UUEMyM+NeLJ8vV28j/ec7xYcH83+/qt3rDo410v4gkqxH0lySfGVLRCk=
  template:
    metadata:
      name: affine-postgres-admin-secret
      namespace: affine
