---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: affine-db-secret
  namespace: affine
spec:
  encryptedData:
    password: AgDPFW8mifMswbcouuVlg2X0uU1y2WXdY45OkPCKyefeVP3TYwlGn3DvQcC4APUJBStcOgM2cbtj1TWL3BglP+2+VLleWV9ss/qbCzpD/s8stcX2dAEe74p/869Sw3oIIn6PxXoddvNDqp6Bugj9D9y23bP/Lsxc5W+5SR69axeV0EooJ7OVdsAyVI8EwivKdHFNGII93fXs4Cym+doiTyOKqi7j+Pv1O4/N+tgXkig9pKlEYdMa52NixZGRst89MNq2PdOVncb5/H+Mx8DGxvk53/613kRzQ4FZnbjkB5cpBUuVOTH2wjA6GcB1hJcgVtrfGS8kSyr8lWAhttIP4VF7FPLRjC7H77CqJdga/192IMz4HKzqR1gkJLzzNAAch8cj/2YWCl+fJgsJXdu+1lLIbSiCJWMGDXttZFp0ODwfRcW5zj6FFyktYXbK83OX/sCTcmBbqV7LPgfXsYSRqT3l4bfOO+n+ZmBhCkUflLl8/lSgl7vaJFTkxi+qtmh8eFf1qAjTSiO96drqvcgbvT30EY7A9VCbHaIugVXZ5x5ZSSGz0otzsV45JqWrYR9LJP02s/X5t14bD/0N0HvINrKd/+QOouTcR9PCuF3D4gMD1vh3HZdGF1/tUJp3OX5H8bvCoUvh99aKuA7JfnQ97yxFyBRPKyi0lOEl/BZdqG8q2kHbxbWG0tR5Fd3C6AwALjhiz4IEXKj5Q84mjhUxFbC3R0s=
  template:
    metadata:
      name: affine-db-secret
      namespace: affine
