---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: affine-db-secret
  namespace: affine
spec:
  encryptedData:
    password: AgBpXjV735bu/3DeLkWgdN3My6pzmbuCndJtcxDOTRkt97y0T1VaezzskF1kIBV0SnyfAgMQLKrCowJPLumRrn5m+lG1nwQ8pqufZUTNNcWcEt5ehCVO0oYAKft/FG0YhXoL9kEGRE8tdhBKDHuABHSieI1RQU+9hHvXexJqQ4qPChX97b0SJhL94rc5pxF5fLJ9oZE9Vv+DHrUBwyzhx1bvVIIlMqNjo6jA5sTi68cdbkmONgboyqOFVhlD44+G5QY5AVERTMX3dsxxOYqQQCd7o1qp3ccNiktHmIO32LSFwf2mzgymea7GtCCDhmNI3YP+xNXgxc4sHHjycREQQZMlZtoGaTw3tQ48mGxwr13BE8aEeN7vG2GTlsDb7+8b8dzZUPyScSB9E6a3rITgHqvpIufznDXMSzfH0ifDJk/uP9b0nyD0BLllbhL4Z+rXs3mJq9aPjqzq8HWK42NKBUGyAb030tmpf4olSurYvN+IgW/fWVgEpX7dsRsZjOQn6tMfqWaY35TKG1gSmdC0loEXlfm3282C6JerT0Jy2MeVJlPLGq0gzVAdt8J47urRZW9oHPBCJJ85bsLyMnRzAQrnkUC8cwxcVrDG5GGpgX+5f56SHIAw1vaDVcX564DPeWJqBUqFprDLpS/oHNuIGu7I7nuVAy6EAqiGUG0i++yFCALT8zlOzGAM4UQVPVD38dEIKG7bkeGwKaq7WcH0+ZlIwl8=
  template:
    metadata:
      name: affine-db-secret
      namespace: affine
