---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: affine-postgres-admin-secret
  namespace: affine
spec:
  encryptedData:
    postgres-password: AgAABSpwoa4Wgrvb369e1mcPwmgUnAQGAQvamFSLkJ1Z8m35aL+aS5VlrQjIbn9n2y9GnQR/yBbBPIuvkW4IgoaKxjsEvSIVzAd+zywxmkBnwi24/I0l+uy3wytnssqgcKe8xi9N3OH6Lil9R9x9akpGc1e1rM+htI9lrBDI7Y7CIMCSQwOhjtzKFn/V5D2EWkjA5ecBAYzaCpH1dZqfyOEJyY289nXf1PfqPIGRIqvmb4XqVwwmN7NnM2/U5gW1Mq3xa6CssDxLWVFDR3XgTZxmrlWuMT5UYyztyV4VQf+LZjt75Psx3iU4rRcODJYEZDkqlz4YE6aFgV9FohEDPEFf5L9+THisWqLeIH8tsV2zkeMWJHqlSNJvZr38BxvZTtM7w6ZDwJ7wlL3GeBkJWqdrctohFyvHK1F8vLYCszemQLBjZAK89B6gtV6J+LVt9/Dv0U8rHuOOQ/rpkV9SMQLhAW0q33/+KtK0vmCX0SgtiTjnSdc/DG3hLVHfsQizQpsfEvrFqQFNMDIQqJ6XGozAceeVk/X+deaZsKD3OgivfwgOyVh/m2o/BJ0WpX0hCCnvtY9y8aaojvbIaIaPubmS/F7cwQ1M+VaKwMSqunEp6jey79UJPGV7iGLSArV60GNRWv2X4q87FlvRVq4KcANxvjFCBWpcaudyL8ltL7pRSQJxxjJ3gmq1oMPVJ4FA0l1TxT9+Nj88ll2AC/TygU/U9A==
  template:
    metadata:
      name: affine-postgres-admin-secret
      namespace: affine
