---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: commafeed-db-secret
  namespace: commafeed
spec:
  encryptedData:
    DB_PASSWORD: AgAeXFvfCD46HYu6vm8aeODKzNoD/zdndoR9bN8y8vozOW4NYXaM+bO1QsvkmxbWYq8XU2QQ+QHK7NG3tcmr8u9ZDI7aY5TwWRCs/mb/9jpCz2sbEsTGIHJ7kLXTfXC8OVMh7GEJ+jubDvPG1p0D5VSXGw+YZXxRAw4EGNcWZqm24FdH375IEqaJBesDxodchyfowjpe4+MOBz5prN0wd4bAyCRQ5NZLhWZONwhc47wb0Qs7SILjuM14c2thoMvjYLU3edSDBlqSURMnJdn2GZpi2pTmxkLLr8RlCqkRm8mEcUjifogtCa0Pwr+FSXOlgcBBcXGNnMParKu9xAwLFEqZ+DCpsBBnWwCRLkC9nFCOA8Tf5y6+rhlP/rajJ1G9uzd6kwXEn4p5KVtgJXMBCPi0+WPHzY7ejpnIlYSmnoOK/QS/O/AMkpNZ0A/jZrCsWTOQLZkbV7uNQ2vq/LePBqFPQdwkOiFuu8japbLVYo+Uq66XdHs5Q+njQNkvPkG0qJ83fZYMwn8SuUW81tmjBQaEntHKirQ1h6ycoPJoVDxzQ2Mukeqcef1oWqIodT2oFzzn7NLZBF2Jh82B2SSQZEfU1rzrmKKq9Mlgn4Oqj6gbkyTEC/Q6vTIkGRu9pp5ytwDQYF2vlS96cgMiEWdTk3hSPbieVMizhkZW1xbpJmsMITQv99C19npNeyvV5SfbipBjxmfgY8+ZZJb+eJJFlsaBTLw1Bg==
  template:
    metadata:
      name: commafeed-db-secret
      namespace: commafeed
