---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAACxkBCEL2yjpnLvzQeW4ofcWxh2vGcA7PcS3bI9weig22d7JuuhVqvZCohyj02g1tzb59GJ/w0nVq8WsA4AltYE/VdFBT3atQA5jhrBOfeM9wjOBDFS6p+zFJtfrxVe3lPE5W4qcsU0vq+peYnIeAMvu6XL+zf+Wb9ihsLBdRb6bDi4okxczc6FU8BJ1me26RdPfaOM8BijbEHQorrgzi5ELmReueE48RPrh3vbY2jCyayu0e7Un9lReJgRjnHl7j+5KtDxSY+7FB9eTPD6O2UN+Sx59X1TI2Q7mu/s3X40K/lk/emfM4cXpBE2yHZ9TepqStS9hf32GlOiXqsbgx1+niPMG1EQO0hIWc8Gi30WqVHkSbmAykmJbIKhm5sEcwEE+ck5+NBMbzn7/cHKEZAjPgX+oPFSnTNMILGjM0Fo0kp7cMgdsGNgKzpNVDVNEhYXKQwX4o5ztJzZF5B/JhNnIInxrszfLuwUBQJRVm3xQxxPjBUFsWZ9ymKW1aHNsdfs/pmpD79Nf6fH31RnMnh51f2Qs2BKmrDNczLyACV3omodZi9wccpTaW2b6Xcp2RHjSIiAmS1TQxiuoQ/+1TA/ngWpCaVnNqKm1jE8HB6Y4ywAR2dFNHeF2pdQ4CoefGGYlGGiLt4fWVYdctEmREtpKwhQO3jHotNE6Q3ws68vIadVDh24+Y5IDNVmELiIvBLp59eTQ/ewfmFrKiW15wHui9Dw==
    admin-user: AgA8mnEzYMMZ0WRgsqwrhpsa4nrUFAW+SR4WHIWbRrChdXZMoapBCFwrsn2Hvb4R8tqWPkVyMmwtrXOeDJUXuxqvv3zkOgkIlEpkS+/gjudyNj8sl5YFtnQAVx5kFT5j4WS89nQwnLPFvpUY7vOlvYIOq9wWFoWe1ru84asPONjDiIvRoleXiNWv/8TZ6ifhBAAoCe3ocvzRzBwHewStMe3FM9M7pelOFvdP03e40F5/unaFmLewfn16jIdgnqMBaQQySzQQFUnja5zydJ6m0Wt9Uq+eCp/2lPa947K2xGz7FFvGpc1upz7xS3v5xnajt+m8TUXlu9gAhHxhtPnt50OkTPyLOQ6oWqlOBCUWwDDnXAiAgsQNf6Jv4Btz5nyTefAbVMvu6HMr5cCF5NmBmS3vFUGBXqI1wLz6hTGhr/XYaEZUZkY/KCfoWW4hiL7l9ZGL1pMPynhqHPlzDGy4kqXJ7BJwMF3pg8XL+Gd3nxfq3UPyMRA0Dk4lri0MiWKry6R8JZL8CO9IlRZ7aefelE+lLC/yUSH2ojye3jjE7UkNvGlNyws5WxA8Ih+YsqMu/AfJz9U6rorI5nQik31EbGZZG9RNf6HZULBogRJzxUnmR7O8P98OMUB1USSl4LPdqRBW7s1HQYb8ImDaQwyF7fcW+u9FyQK+hKMYWZb1XmqzR2Z0mPhoX2yQ8ycZ/gGiXT7bcvVvJg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
