apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-credentials
  namespace: openclaw
spec:
  encryptedData:
    OPENAI_API_KEY: AgBXZ2pRohELlS4Az/nja/fAZIP4JPnaJ2jefxg9z92ZysCwWylea5Gb0+PC0b0J/ekePUagBwECFSgWT4D/oVaZUKNPCSPFkMLdiCSSKUSe2wDj78CnUkeQZS1qevt+r9UZEOMIeZD/8JQb+tiDwHp9a/69R4GusgevHNBgaU3Hf8zcPx5UkRDcaudYtCkbXTuDjIhB4FNbPS2KHTkyb0v7vKJCIAUWEhp1RfMeEC7LwJRs88AElsWGAWbEzlEhiMeFHrkQjgwfQibvxTfLKedGutxX/XcyrkEIZ8b+FQd0J2pR69IHlN1QaXWEKZ64j0wXWVG1Wie557uzxrdiGufIDPlfysAEmaoHyTq7VCmEG8ygZp/IyQ9aUoAbrinK2b8vX9c8rQU7cw92Jzr5FjVqARMMC5W/hfByOPaZ+C7OZRs5Gy/9VpYB8HaOYfchGYbgas0nYsbpfplTkk9AaHTOce2y28fF9UG/pxOcXyURAkM8Jm173DQvWiY5GCCDAIaw4135VKj/Jus9XL41AoJ/y+ih22Cb4gwCmlwtF6N4yU75D/4WqMfwLazwBh4J1wikX7SxYYgk6CQMwV7i8UUwufEx+UWBs+iXwtqciyh/A8hZSggwLaIqw+xKVKtHY6enAvhLHPcgsFZKVYgasz0Y9L93A2iLhhb8PQv0sGAYJlwqp6Mc4mk1qSXW6IW3XqFSbrNhx8bQMXVAG/DVXdZCjQTZ1uLv4sehJ/wXhqjyMpuHB42Rn4YgBmcjZ/HeRosP4d3VFY6Gz2ZTu35JL0xi0YGoBznTKhHGxFuqE2r/bQ69vCUW5r36VSjTw6KkWroH6OGwsu26SgjCCc8bGGQc2LNE4iV1z1joo4cHJtwO9YTYTiWbrN/HKGivayTDkpNhRPYZ3VmfODyLs9xAlhA6r68Ztw==
  template:
    metadata:
      name: openclaw-credentials
      namespace: openclaw
    type: Opaque
