---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
spec:
  encryptedData:
    password: AgAgn7x+0gHTVUDLb7LWvQ7LuiPAqh4Zn2J8vXaL1SCiADjPwPC2Y+Go+h57swR/Qr8Lz4ANCoHxaij6KnvPWt9Qt6QGQcg4XDMrSbc9ybZgYWyrVRsXHDClymIg7/4e9BHqTljzqVgXHHrCJuJzfQ/rfmkMJaEyBVoAf6Lj5uiWkyEXzaXBsz4SUs/bCY9o049Ww1AN3ZGwrQ3DQVAP6CxkI3eGZXOxwen1mHF/OvnhrCuPaaIldLcaDzYqBml0rxdDexnafW39sHts6uhRj/YtiYancsWZr/THu1TKGmyyWuY+Jz6UyFtK7cmGljOI0HvvfjURa2mgFSKiu+ncxlByR9i8o+xN7Q/DB3jaS2HcXtxmZPy9zRtaY8pm4UrFPnYjN+NJ3SSSTr0RO5DCIA1Z1/lKhrQLdSgFdUuiHoL6udCqLSb2aaNaQE+Vl6lBra7ZraaRFHT9ylt2/x9s4PCxl61pwxcsgR07tjSM8DBRF0jQ3xwY9AZe4U68JDU9ZO/QSkYx6/r1IY/qB4pbibpVFeSDmS0s/58QGkE5RJmg1T3h5rhmIqToWhD0Pz88Wrmgbck22EVBTsZ6h14CPsqmpZiJ6eyLmel7rXj/mASBoWJroqkqZpC1nHs5NJMUe58cAeFMOGSrIJpg/SDQr6EwNYKHBS0PtX+md3taud+GCdJBeC7DDpdBLDCtSwKfoNb08juekVzoM7Z+9+cBeWOB1xQ=
  template:
    metadata:
      name: pgadmin-secret
      namespace: pgadmin
