---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plane-helm-values
  namespace: plane
spec:
  encryptedData:
    values.yaml: AgAEU2bKfaN0CX5gi8njjTNBaHx5U7uzkCZ2J3BqQCVnAOXtK8adllGPPDgPoecIEsnwdcmwOAWDdZsgaJgGJg/h3nYXWOxOGWk5WLFkDi+lBkzBodMF/UMy4s+J2pNCpbXMpj6wkRAToKvhXkODKq8+CG+VIzwbBnzvmj2C9D9bsVW+swjxLp1VnNkLlE7klZnwY8h2lSqVVyQt8FhnP+EjBLEhJc1yZVgkZk8EL13PnzVBtxa6qvqUrtsN80YGy7PuTzo4hS1wUgjfmBeEX1Fp1VZA9w8Kz/VaoQA5ttJbRBQ07dhGeKI7g1alF8/z1WNyf8GemquGA+pjwxwcUyNHd9MjfvQ66Qn/AgLdJMA3peaOgB//qKNuZ+qWu67tLULs7r3ko5c0Vu1DVSCZAku/bwe4jws2SZcHjrJi+OGord3b8m1iTrRfTHaxW0z1vVZiYrTHFjd/EMEFqlRBlfne/kWCaQ/gYHZBaLTtvjMGsLxf9HlSXe8Ukd7SigvBYDxs0wrjZmav88sDoxlFkdY+5T+FsBxFN7PlBhlL2jA5P0o6/J9ypPcUcMP3C1c8uQOqF5d2CjEik/FcsciXnKyEXGGO5D5m0pa8q5Q6jHNnXPZWkQyHtfN48ODK8C0W9LoW0H2s2lOtFoULlqeEh0XSDRvIC2aBfHBB5xr4grbkdSrCjvnScXkgjHzrfUyedsLvfytTYafzawCkg+ykPEOdZ8QhKKEYn54/wg69pJOU3MQtrOONQroVGgcitYsTpZCGnUrBwsVI03K3WaOKZAMcCTczcSuV547ZM5NNlbqWqJWzb3y6hjWTG9qAP/gJlcpKoSRco9ut4SyghbCAs3ivXhGRas/sQdfjRPfJzkhjumAUODMZHywzjzzGRfotw64Qx/Ulji5erBo2J0W/CK+gZN2X3+KMj2lX3ouxj+30noJUz/NORsIqAkGZYcETSwb6VMHWh0F2U3rWnb/szk5Ditu+cXzXr3wTAnbyyTchDvh7lE1WdamW2G/0cEUIVZGRwvkg8X/58a1E9NIETSnms8To6WN6YML2GuiFmdLW/W0wbnmWH5Q9VhidVREncj7wzYez7kkNfiPKCpZZg+2jG9kS3rm3ROyidZLojKGmb7er8B4/48cvqOi4qs/vAoKn3nvBDCvD6afc2nzjWIkN00CJWwUYjLC9QDePhqrRm/+HkPIVwpccybcukCP/im1QLh+O8PK4o2j/VbW2Ys0F/xYQ
  template:
    metadata:
      name: plane-helm-values
      namespace: plane
    type: Opaque
