---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plane-rabbitmq-secret
  namespace: plane
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgC0VoD0mTwbdpBXBUAiE3BPwc9e7eEWT3fHVmBna5fapakbuV36Y5rt5yQ5NdG062WVZEWbZlQ+koD7qnE5BiJmXF2lMbIS+dZXHmbdbdfMK75357xm84QTgTL49Io2aWaDT0tWSFsGWf3AkkF1Y6Bhiwic8+zivRJPSXrp4qiepM9e7yX31EZxJbQ8sWpYgEp/QoDhYV1ATXfMdP40fz2i4tBi7QBb0ehef3FhFkviXCu6YUiQGVIuCFOHcPE1t7raLj6qt1n9cTE2PAFZQRIcUDqdA4o+njlWhyjx1j/D3h54zBuuSaofmwaTgQMw9UgkTgIYtegydtDq1+7H14VxnC8dFaPDMRKqrFp9HSovP07HRPAqUjpNGuI2aRaIpj/Yjpm1ihdjuEn8l79e9SCPzvw5ZizZiTfQJQcTJ1LAbWVL4+SVNe6m35pwOOxfCuDhzBWSTmQ2r7Qus9nPUaSt8xP9DJOyp9u3qEyYfUoQmycfMdg9wpOZHQBXNllyQEkxZYzux3mvADFZRoPu3+Rp0lTtu9Dd3vCUB+EucXTWXbvDL4BKbje/0KnU8PH1iM6+4e6XNdY/fXT30mqjvx2ZTmm3jAj4PH6NGeqfJ8/S8iPYTMQ+lfzLKlT+M19bwSCf8qoP+5KbSUV/2WtzSm2J+r98qjseD7BqLF2eel5BhCeITqlujwvwdndUNTeQeFhm6gQqM+/3X2jvllPcmGNfS6eQYS2aKizkk/saGkQp
    RABBITMQ_DEFAULT_USER: AgACqOYfBlBvBVLT0IPP+Vd5SE54ulZigFxfjNUi4U+xAcEX3fyjuQe0N1DiWe8V1cvVQLqRiIAc1sywX2iHNDlaB1rfWnKQmF5Wban1JFEcLSMw2LhthFLA3EYEOybnbhvaYmRM1UT30/VJTwcKg5JR28qXt8JaSB3ZnOJp3qhySEihh6wksEoXcde2UMXB+BHfqc/2BfdD4m2SghDwup76JoQlh7XZ5MZrltSxy9QXXsG69Qpj4aYd7P/T1RdSWycmjbYCU0BufSlGwWhUeiKDL4shWSrBa3qdG+dwS2cn/uMV5+AZ1VQTf8E2eu6iFtv10mQs/MkPjUFIt0/1W8oOeH0mWMTeWoG3NIi8TgWh1c3M9ztzakDEpsI+gxKdAeszVI5CD460+qhjnKAVl2vK1fRix/oYaGXv9FUKdqj9PNb7GdKEVn7SYIYwdqkUgWZ8/4dqYd2/GkMLIcHBpvjRaIq56CXOTXl+BBU1Up3wOemIHO3Zy0z1NhnR/qB82eAC1R7N/osN3Ueq1HC/mMUz/+D4mQQqgmbCHHcDXyhgrkOtQQsUKFImL2oAispV+jezjJCRiLFf//OXI5ex68TsvzJyM+tE0bd0n/Ts+lG/8LvFX7lkSJHHC+O/Itoz4q/yWyhWIACP/4SkgB0hqXe5eU6SZ5r7Zk+qcCEftYd03Uy8E+6IK782HsVruDMplzsOk2lN9w==
  template:
    metadata:
      name: plane-rabbitmq-secret
      namespace: plane
    type: Opaque
