image:
  repository: linuxserver/transmission
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 9091

ingress:
  host: torrent.192.168.68.150.nip.io

env:
  PUID: "1000"
  PGID: "1000"
  TZ: UTC

persistence:
  config:
    storageClass: nfs-hdd
    size: 1Gi
  downloads:
    size: 500Gi
    nfs:
      server: 192.168.68.100
      path: /mnt/pve/BigData/k3s-shares/transmission

resources:
  requests:
    memory: 64Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - worker

topologySpread:
  enabled: true

