apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.4
    helm:
      values: |
        crds:
          enabled: true
        installCRDs: true
        replicaCount: 1
        extraObjects:
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: homelab-ca-issuer
            spec:
              ca:
                secretName: homelab-ca-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
