---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBqMyX3NXG9VKuHOSro0WV5XTzQWPRMqL8H2jQwb609Q4y18vi1WuK3oYqy1UiL6R8TThxLX978UxA/yEGZ8f30ldOrIZGhzSUnqMB5NJ9YcsYvQuybQaGdRpCeAhLoBNJNFQZ4qp1vyo666gfaedPQb+u/kjKPZfLO7E43ZXViQEY6yqflefZvvkh5h8kdwBBO1A2XSNT7wAKO1TQlNB6Scv8ibPmONnITIvbFwyrlFPr/MC6L5MyGTf+OK6xd1KIfvlXKNkiGKKro9b7QYRyeywYhdmTmudWJg1TuLV3xxGtFyr054hZDuRUdFDF1ZGygCdlfDEVRjmjK5xkJrtfSLswDu/oTMr2S6bZTvpPJ6T0i1U53bV5kJj+qPBAf+PqllPkNuTuvjf0f+rI0pk7RM4w3PCoPYHdjM1UJ8Ugmr+6cYnHmvNHj7VF6slSlwzZ8WCq8FNTAQiR/W8M655rIMRgg4RSXp/QToi4Xh2LTdqB3tDy7WdkdX/iNMhgAPnddPzDy1PoajBJG8E+vFh+moFPtg1rkiOp+2hNw72mdTBe0OJFQrvTvUq+Hzb4A6fXRoJql0QG4rZ8vHiiT41lcN/EeGxC9dnYzRpQ67qYQ/7SdN/97n2kUDlPaSoC6WMrdVEoV1pm2SRBl/d0Zy4NtgUr9kVaYb77PmQfIkTzWuJTgENPMy5whvQf4zl4wqjO3wMgrjvLT5GU6SKhVl5RqEB6ACmsypzEW+8yJ80sU0YbL+1lqHdQ9
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
