---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin-secret
  namespace: databases
spec:
  encryptedData:
    postgres-password: AgCfni95BgnADysyZAhREXihU6ZZ6spwmdzrQRQa9pYRA6TTljj03PaY1J/dHFh5z3AlYNq/ry30bLaCVKQzsTWgouFDZzOOfDq4KrjQabPwt/LOO6HB5DGwO+Gdb0Vgxb/LMxrzXB4pVlXKsIRjCbzW525Ni3Lr9BY1CMLtsXPx8m9+CnrGHGfKb/EUb1TJfAyJKBos7JNG+vtyE9GluxOZYHAz8Wfa+ZNmdxhHauSG2SUtYRCNo1pk+indBYE7grLeO6/MZ5cOLdkw3pXCpVrZTHfWC1/dtNWtZoKob8RyRxqMrZznabuKmzuG+xW5YxlBcKwNYF6b0Uw6H6dL4tHDrJ6ZNcVqk51HHzGh2wPrh3LOilQFquCoJw5jHKlo8b+jImOkUHH6sddLEoQUlQnBKwXVaAdoa9AnGFHsMq7+w4UAVt20rBMElP6If5i0Pm6O5FJdSqBgss4A4oq8dKOq2oWPiulutedoTupoy5nFneXndDYgBfH97YFyqayjttPV8G1YzLS+QxFSzefKl1vRZkwdNndSQVhQRWKD7vwwgobD87tGyOxfEuiHcNUcEZNFuV04Fi95SpN0D7/7nWW8A1ocvL2667UAdT6KGxdiDj1rrDGqrDCK4eA+fljT6PC7RdJf7X+pxm5jGwrClSs8yjz29xwS7QwaA2xAd1r9Ud5bspIGk04PBp/tAI7gXbPIy33Q2XXRY16lpXs=
  template:
    metadata:
      name: postgres-admin-secret
      namespace: databases
