apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.26.0
    helm:
      values: |
        replicaCount: 1
        image:
          repository: pihole/pihole
          tag: latest
          pullPolicy: IfNotPresent

        serviceDns:
          type: LoadBalancer
          port: 53
          annotations:
            metallb.io/loadBalancerIPs: 192.168.68.200
        serviceWeb:
          type: ClusterIP
          http:
            enabled: true
            port: 80
          https:
            enabled: false
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            cert-manager.io/cluster-issuer: homelab-ca-issuer
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - pihole.local
          tls:
            - secretName: pihole-tls
              hosts:
                - pihole.local
        adminPassword: "01cd01e1"
        DNS1: "8.8.8.8"
        DNS2: "8.8.4.4"
        extraEnvVars:
          TZ: UTC
        dnsmasq:
          customDnsEntries:
            - address=/local/192.168.68.150
        persistentVolumeClaim:
          enabled: true
          storageClassName: nfs-hdd
          accessModes:
            - ReadWriteOnce
          size: 1Gi
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
