apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commafeed
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrashed98/homelab.git
    targetRevision: master
    path: helm/commafeed
  destination:
    server: https://kubernetes.default.svc
    namespace: commafeed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
