apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.7.0
    chart: jellyfin
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - host: jellyfin.local
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          config:
            enabled: true
            storageClass: nfs-hdd
            size: 10Gi
          media:
            enabled: true
            type: nfs
            server: 192.168.68.100
            path: /mnt/pve/BigData/k3s-share/media
        service:
          type: ClusterIP
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 4Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
