apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.runix.net
    chart: pgadmin4
    targetRevision: "1.59.0"
    helm:
      values: |
        env:
          email: admin@homelab.com

        existingSecret: pgadmin-secret
        secretKeys:
          pgadminPasswordKey: password

        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            cert-manager.io/cluster-issuer: homelab-ca-issuer
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
          paths:
            - path: /pgadmin
              pathType: Prefix
          tls:
            - secretName: pgadmin-tls

        serverDefinitions:
          enabled: true
          servers:
            "1":
              Name: Homelab PostgreSQL
              Group: Servers
              Port: 5432
              Username: postgres
              Host: postgres.databases.svc.cluster.local
              SSLMode: prefer
              MaintenanceDB: postgres

        persistentVolume:
          enabled: true
          storageClass: nfs-hdd
          size: 1Gi

        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
