apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.plane.so/
    chart: plane-ce
    targetRevision: "1.4.1"
    helm:
      values: |
        planeVersion: v1.4.1

        # This tells the chart to look for your secret 'plane-helm-values'
        # for database and environment configurations
        external_secrets:
          pgdb_existingSecret: "plane-helm-values"
          app_env_existingSecret: "plane-helm-values"
          rabbitmq_existingSecret: "plane-helm-values"

        ingress:
          enabled: true
          appHost: plane.voltafinancials.com
          # These must be set or the ingress resource might be invalid
          minioHost: plane-minio.voltafinancials.com
          rabbitmqHost: plane-mq.voltafinancials.com
          ingressClass: traefik
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"

        postgres:
          local_setup: false

        redis:
          local_setup: false

        rabbitmq:
          local_setup: true
          default_user: plane
          storageClass: nfs-hdd

        minio:
          local_setup: true
          root_user: plane-minio
          storageClass: nfs-hdd
  destination:
    server: https://kubernetes.default.svc
    namespace: plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
