apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.gabe565.com
    targetRevision: 0.16.1
    chart: vaultwarden
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - host: vault.local
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          data:
            enabled: true
            type: nfs
            nfs:
              server: 192.168.68.100
              path: /mnt/pve/BigData/k3s-share/vaultwarden
        env:
          DOMAIN: https://vault.local
          SIGNUPS_ALLOWED: "true"
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
