apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xtreme-downloader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrashed98/xtreme-downloader.git
    targetRevision: master
    path: helm/xtreme-downloader
    helm:
      values: |
        ingress:
          host: xtreme.192.168.68.150.nip.io
        media:
          nfsServer: 192.168.68.100
          nfsPath: /mnt/pve/BigData/k3s-shares/media
  destination:
    server: https://kubernetes.default.svc
    namespace: xtreme-downloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
