image:
  repository: vaultwarden/server
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: vault.voltafinancials.com

env:
  DOMAIN: https://vault.voltafinancials.com
  SIGNUPS_ALLOWED: "true"
  WEBSOCKET_ENABLED: "true"

resources:
  requests:
    memory: 32Mi
    cpu: 25m
  limits:
    memory: 128Mi
    cpu: 100m

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - worker

topologySpread:
  enabled: true

