image:
  repository: ghcr.io/mrashed98/learning-log
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: log.local

resources:
  requests:
    memory: 32Mi
    cpu: 25m
  limits:
    memory: 64Mi
    cpu: 100m

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: Exists

topologySpread:
  enabled: false
